devicehub-django/api/urls.py
from api import views

from django.urls import path


app_name = 'api'

urlpatterns = [
    path('v1/snapshot/', views.NewSnapshotView.as_view(), name='new_snapshot'),
    path('v1/annotation/<str:pk>/', views.AddAnnotationView.as_view(), name='new_annotation'),
    path('v1/device/<str:pk>/', views.DetailsDeviceView.as_view(), name='device'),
    path('v1/tokens/', views.TokenView.as_view(), name='tokens'),
    path('v1/tokens/new', views.TokenNewView.as_view(), name='new_token'),
    path("v1/tokens/<int:pk>/edit", views.EditTokenView.as_view(), name="edit_token"),
    path('v1/tokens/<int:pk>/del', views.TokenDeleteView.as_view(), name='delete_token'),
]

devicehub-django/dashboard/urls.py
from django.urls import path
from dashboard import views 

app_name = 'dashboard'

urlpatterns = [
    path("", views.UnassignedDevicesView.as_view(), name="unassigned_devices"),
    path("<int:pk>/", views.LotDashboardView.as_view(), name="lot"),
    path("search", views.SearchView.as_view(), name="search"),
]

devicehub-django/dhub/urls.py
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    # path('api/', include('snapshot.urls')),
    path("", include("login.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("evidence/", include("evidence.urls")),
    path("device/", include("device.urls")),
    path("admin/", include("admin.urls")),
    path("user/", include("user.urls")),
    path("lot/", include("lot.urls")),
    path('api/', include('api.urls')),
]

if settings.DPP:
    urlpatterns.extend([
        path('dpp/', include('dpp.urls')),
        path('did/', include('did.urls')),
    ])

devicehub-django/lot/urls.py
from django.urls import path
from lot import views

app_name = 'lot'

urlpatterns = [
    path("add/", views.NewLotView.as_view(), name="add"),
    path("delete/<int:pk>/", views.DeleteLotView.as_view(), name="delete"),
    path("edit/<int:pk>/", views.EditLotView.as_view(), name="edit"),
    path("add/devices/", views.AddToLotView.as_view(), name="add_devices"),
    path("del/devices/", views.DelToLotView.as_view(), name="del_devices"),
    path("tag/<int:pk>/", views.LotsTagsView.as_view(), name="tag"),
    path("<int:pk>/document/", views.LotDocumentsView.as_view(), name="documents"),
    path("<int:pk>/document/add", views.LotAddDocumentView.as_view(), name="add_document"),
    path("<int:pk>/annotation", views.LotAnnotationsView.as_view(), name="annotations"),
    path("<int:pk>/annotation/add", views.LotAddAnnotationView.as_view(), name="add_annotation"),
]

devicehub-django/documents/models.py
from django.db import models

# Create your models here.

devicehub-django/lot/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from utils.constants import (
    STR_SM_SIZE,
    STR_SIZE,
    STR_EXTEND_SIZE,
)

from user.models import User, Institution
# from device.models import Device
# from evidence.models import Annotation


class LotTag(models.Model):
    name = models.CharField(max_length=STR_SIZE, blank=False, null=False)
    owner = models.ForeignKey(Institution, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class DeviceLot(models.Model):
    lot = models.ForeignKey("Lot", on_delete=models.CASCADE)
    device_id = models.CharField(max_length=STR_EXTEND_SIZE, blank=False, null=False)


class Lot(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=STR_SIZE, blank=True, null=True)
    code = models.CharField(max_length=STR_SIZE, blank=True, null=True)
    description = models.CharField(max_length=STR_SIZE, blank=True, null=True)
    closed = models.BooleanField(default=False)
    owner = models.ForeignKey(Institution, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    type = models.ForeignKey(LotTag, on_delete=models.CASCADE)

    def add(self, v):
        if DeviceLot.objects.filter(lot=self, device_id=v).exists():
            return
        DeviceLot.objects.create(lot=self, device_id=v)
        
    def remove(self, v):
        for d in DeviceLot.objects.filter(lot=self, device_id=v):
            d.delete()


class LotAnnotation(models.Model):
    class Type(models.IntegerChoices):
        SYSTEM= 0, "System"
        USER = 1, "User"
        DOCUMENT = 2, "Document"

    created = models.DateTimeField(auto_now_add=True)
    lot  = models.ForeignKey(Lot, on_delete=models.CASCADE)
    owner = models.ForeignKey(Institution, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    type =  models.SmallIntegerField(choices=Type) 
    key = models.CharField(max_length=STR_EXTEND_SIZE)
    value = models.CharField(max_length=STR_EXTEND_SIZE)

devicehub-django/lot/forms.py
from django import forms
from lot.models import Lot


class LotsForm(forms.Form):
    lots = forms.ModelMultipleChoiceField(
        queryset=Lot.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    def clean(self):
        self._lots = self.cleaned_data.get("lots")
        return self._lots
    
    def save(self, commit=True):
        if not commit:
            return

        for dev in self.devices:
            for lot in self._lots:
                lot.add(dev.id)
        return

    def remove(self):
        for dev in self.devices:
            for lot in self._lots:
                lot.remove(dev.id)
        return

devicehub-django/documents/views.py
from django.shortcuts import render

# Create your views here.

devicehub-django/lot/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import TemplateView
from django.views.generic.edit import (
    CreateView,
    DeleteView,
    UpdateView,
    FormView,
)
from dashboard.mixins import DashboardView
from lot.models import Lot, LotTag, LotAnnotation
from lot.forms import LotsForm


class NewLotView(DashboardView, CreateView):
    template_name = "new_lot.html"
    title = _("New lot")
    breadcrumb = "lot / New lot"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    model = Lot
    fields = (
        "type",
        "name",
        "code",
        "description",
        "closed",
    )

    def form_valid(self, form):
        form.instance.owner = self.request.user.institution
        form.instance.user = self.request.user
        response = super().form_valid(form)
        return response


class DeleteLotView(DashboardView, DeleteView):
    template_name = "delete_lot.html"
    title = _("Delete lot")
    breadcrumb = "lot / Delete lot"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    model = Lot
    fields = (
        "type",
        "name",
        "code",
        "description",
        "closed",
    )

    def form_valid(self, form):
        response = super().form_valid(form)
        return response


class EditLotView(DashboardView, UpdateView):
    template_name = "new_lot.html"
    title = _("Edit lot")
    breadcrumb = "Lot / Edit lot"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    model = Lot
    fields = (
        "type",
        "name",
        "code",
        "description",
        "closed",
    )

    def get_form_kwargs(self):
        pk = self.kwargs.get('pk')
        self.object = get_object_or_404(
            self.model,
            owner=self.request.user.institution,
            pk=pk,
        )
        # self.success_url = reverse_lazy('dashbiard:lot', args=[pk])
        kwargs = super().get_form_kwargs()
        return kwargs


class AddToLotView(DashboardView, FormView):
    template_name = "list_lots.html"
    title = _("Add to lots")
    breadcrumb = "lot / add to lots"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    form_class = LotsForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lots = Lot.objects.filter(owner=self.request.user.institution)
        lot_tags = LotTag.objects.filter(owner=self.request.user.institution)
        context.update({
            'lots': lots,
            'lot_tags':lot_tags,
        })
        return context

    def get_form(self):
        form = super().get_form()
        form.fields["lots"].queryset = Lot.objects.filter(owner=self.request.user.institution)
        return form

    def form_valid(self, form):
        form.devices = self.get_session_devices()
        form.save()
        response = super().form_valid(form)
        return response


class DelToLotView(AddToLotView):
    title = _("Remove from lots")
    breadcrumb = "lot / remove from lots"

    def form_valid(self, form):
        form.devices = self.get_session_devices()
        form.remove()
        response = super().form_valid(form)
        return response


class LotsTagsView(DashboardView, TemplateView):
    template_name = "lots.html"
    title = _("lots")
    breadcrumb = _("lots") + " /"
    success_url = reverse_lazy('dashboard:unassigned_devices')

    def get_context_data(self, **kwargs):
        self.pk = kwargs.get('pk')
        context = super().get_context_data(**kwargs)
        tag = get_object_or_404(LotTag, owner=self.request.user.institution, id=self.pk)
        self.title += " {}".format(tag.name)
        self.breadcrumb += " {}".format(tag.name)
        show_closed = self.request.GET.get('show_closed', 'false') == 'true'
        lots = Lot.objects.filter(owner=self.request.user.institution).filter(type=tag, closed=show_closed)
        context.update({
            'lots': lots,
            'title': self.title,
            'breadcrumb': self.breadcrumb,
            'show_closed': show_closed
        })
        return context


class LotAddDocumentView(DashboardView, CreateView):
    template_name = "new_annotation.html"
    title = _("New Document")
    breadcrumb = "Device / New document"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    model = LotAnnotation
    fields = ("key", "value")

    def form_valid(self, form):
        form.instance.owner = self.request.user.institution
        form.instance.user = self.request.user
        form.instance.lot = self.lot
        form.instance.type = LotAnnotation.Type.DOCUMENT
        response = super().form_valid(form)
        return response

    def get_form_kwargs(self):
        pk = self.kwargs.get('pk')
        self.lot = get_object_or_404(Lot, pk=pk, owner=self.request.user.institution)
        self.success_url = reverse_lazy('lot:documents', args=[pk])
        kwargs = super().get_form_kwargs()
        return kwargs


class LotDocumentsView(DashboardView, TemplateView):
    template_name = "documents.html"
    title = _("New Document")
    breadcrumb = "Device / New document"

    def get_context_data(self, **kwargs):
        self.pk = kwargs.get('pk')
        context = super().get_context_data(**kwargs)
        lot = get_object_or_404(Lot, owner=self.request.user.institution, id=self.pk)
        documents = LotAnnotation.objects.filter(
            lot=lot,
            owner=self.request.user.institution,
            type=LotAnnotation.Type.DOCUMENT,
        )
        context.update({
            'lot': lot,
            'documents': documents,
            'title': self.title,
            'breadcrumb': self.breadcrumb
        })
        return context


class LotAnnotationsView(DashboardView, TemplateView):
    template_name = "annotations.html"
    title = _("New Annotation")
    breadcrumb = "Device / New annotation"

    def get_context_data(self, **kwargs):
        self.pk = kwargs.get('pk')
        context = super().get_context_data(**kwargs)
        lot = get_object_or_404(Lot, owner=self.request.user.institution, id=self.pk)
        annotations = LotAnnotation.objects.filter(
            lot=lot,
            owner=self.request.user.institution,
            type=LotAnnotation.Type.USER,
        )
        context.update({
            'lot': lot,
            'annotations': annotations,
            'title': self.title,
            'breadcrumb': self.breadcrumb
        })
        return context


class LotAddAnnotationView(DashboardView, CreateView):
    template_name = "new_annotation.html"
    title = _("New Annotation")
    breadcrumb = "Device / New annotation"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    model = LotAnnotation
    fields = ("key", "value")

    def form_valid(self, form):
        form.instance.owner = self.request.user.institution
        form.instance.user = self.request.user
        form.instance.lot = self.lot
        form.instance.type = LotAnnotation.Type.USER
        response = super().form_valid(form)
        return response

    def get_form_kwargs(self):
        pk = self.kwargs.get('pk')
        self.lot = get_object_or_404(Lot, pk=pk, owner=self.request.user.institution)
        self.success_url = reverse_lazy('lot:annotations', args=[pk])
        kwargs = super().get_form_kwargs()
        return kwargs

devicehub-django/lot/templates/annotations.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>Lot {{ lot.name }}</h3>
  </div>
</div>

<div class="row">
  <div class="tab-pane fade show active" id="details">
    <div class="btn-group dropdown ml-1 mt-1" uib-dropdown="">
      <a href="{% url 'lot:add_annotation' lot.pk %}" class="btn btn-primary">

        <i class="bi bi-plus"></i>
        Add new annotation
        <span class="caret"></span>
      </a>
    </div>

    <h5 class="card-title mt-2">Annotations</h5>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Key</th>
          <th scope="col">Value</th>
          <th scope="col" data-type="date" data-format="YYYY-MM-DD hh:mm">Created on</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
	{% for a in annotations %}
      <tr>
        <td>{{ a.key }}</td>
        <td>{{ a.value }}</td>
        <td>{{ a.created }}</td>
        <td></td>
        <td></td>
      </tr>
      {% endfor %}
        
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

devicehub-django/lot/templates/delete_lot.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

{% load django_bootstrap5 %}
<div class="row mb-3">
  <div class="col">
    Are you sure than want remove the lot {{ object.name }} with {{ object.devices.count }} devices.
  </div>
</div>

<form role="form" method="post">
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
  <div class="message">
    {% for field, error in form.errors.items %}
      {{ error }}<br />
    {% endfor %}
    <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}
{% bootstrap_form form %}
<div class="form-actions-no-box">
  <a class="btn btn-grey" href="{% url 'dashboard:unassigned_devices' %}">{% translate "Cancel" %}</a>
  <input class="btn btn-green-admin" type="submit" name="submit" value="{% translate 'Delete' %}" />
</div>

</form>
{% endblock %}

devicehub-django/lot/templates/documents.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>Lot {{ lot.name }}</h3>
  </div>
</div>

<div class="row">
  <div class="tab-pane fade show active" id="details">
    <div class="btn-group dropdown ml-1 mt-1" uib-dropdown="">
      <a href="{% url 'lot:add_document' lot.pk %}" class="btn btn-primary">

        <i class="bi bi-plus"></i>
        Add new document
        <span class="caret"></span>
      </a>
    </div>

    <h5 class="card-title mt-2">Documents</h5>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Key</th>
          <th scope="col">Value</th>
          <th scope="col" data-type="date" data-format="YYYY-MM-DD hh:mm">Created on</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
	{% for a in documents %}
      <tr>
        <td>{{ a.key }}</td>
        <td>{{ a.value }}</td>
        <td>{{ a.created }}</td>
        <td></td>
        <td></td>
      </tr>
      {% endfor %}
        
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

devicehub-django/lot/templates/list_lots.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

<form method="post">
  {% csrf_token %}

{% for tag in lot_tags %}
<div class="row">
  <div class="col-lg-3 col-md-4 label ">{{ tag }}</div>
</div>

{% for lot in lots %}
{% if lot.type == tag %}
<div class="row">
  <div class="col-lg-3 col-md-4 label "><input type="checkbox" name="lots" value="{{ lot.id }}" /></div>
  <div class="col-lg-3 col-md-4 label ">{{ lot.name }}</div>
</div>
{% endif %}
{% endfor %}
{% endfor %}

  <button class="btn btn-green-admin" type="submit">Save</button>
</form>

{% endblock %}

devicehub-django/lot/templates/lots.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row mb-3">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
  <div class="col text-center">
    {% if show_closed %}
      <a href="?show_closed=false" class="btn btn-green-admin">
        {% trans 'Hide closed lots' %}
      </a>
    {% else %}
      <a href="?show_closed=true" class="btn btn-green-admin">
        {% trans 'Show closed lots' %}
      </a>
    {% endif %}

    <a href="{% url 'lot:add' %}" type="button" class="btn btn-green-admin">
      <i class="bi bi-plus"></i>
      {% trans 'Add new lot' %}
    </a>
  </div>
</div>

<div class="row">
  <table class= "table table-striped table-sm">
  {% for lot in lots %}
    <tr>
      <td><a href="{% url 'dashboard:lot' lot.id %}">{{ lot.name }}</a></td>
      <td>
        <a href="{% url 'lot:edit' lot.id %}"><i class="bi bi-pen"></i></a>
      </td>
      <td>
        <a href="{% url 'lot:delete' lot.id %}"><i class="bi bi-trash text-danger"></i></a>
      </td>
    </tr>
  {% endfor %}
  </table>
</div>

{% endblock %}

devicehub-django/lot/templates/new_annotation.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

{% load django_bootstrap5 %}
<form role="form" method="post">
  {% csrf_token %}
  {% if form.errors %}
  <div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
    <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
    <div class="message">
      {% for field, error in form.errors.items %}
        {{ error }}<br />
      {% endfor %}
      <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
  {% endif %}
  {{ form.management_form }}
  <div class="container" id="formset-container">
    <div class="row mb-2">
      <div class="col"></div>
    </div>
    {% for f in form %}
      <div class="row mb-2">
        <div class="col">
          {% bootstrap_field f %}
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="container">
    <a class="btn btn-grey" href="{% url 'dashboard:unassigned_devices' %}">{% translate "Cancel" %}</a>
    <input class="btn btn-green-admin" type="submit" name="submit" value="{% translate 'Save' %}" />
  </div>

</form>

{% endblock %}

devicehub-django/lot/templates/new_lot.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

{% load django_bootstrap5 %}
<form role="form" method="post">
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
  <div class="message">
    {% for field, error in form.errors.items %}
      {{ error }}<br />
    {% endfor %}
    <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}
{% bootstrap_form form %}
<div class="form-actions-no-box">
  <a class="btn btn-grey" href="{% url 'dashboard:unassigned_devices' %}">{% translate "Cancel" %}</a>
  <input class="btn btn-green-admin" type="submit" name="submit" value="{% translate 'Save' %}" />
</div>

</form>
{% endblock %}