devicehub-django/admin/urls.py
from django.urls import path
from admin import views

app_name = 'admin'

urlpatterns = [
    path("panel/", views.PanelView.as_view(), name="panel"),
    path("users/", views.UsersView.as_view(), name="users"),
    path("users/new", views.CreateUserView.as_view(), name="new_user"),
    path("users/edit/<int:pk>", views.EditUserView.as_view(), name="edit_user"),
    path("users/delete/<int:pk>", views.DeleteUserView.as_view(), name="delete_user"),
    path("institution/<int:pk>", views.InstitutionView.as_view(), name="institution"),
]

devicehub-django/api/urls.py
from api import views

from django.urls import path


app_name = 'api'

urlpatterns = [
    path('v1/snapshot/', views.NewSnapshotView.as_view(), name='new_snapshot'),
    path('v1/annotation/<str:pk>/', views.AddAnnotationView.as_view(), name='new_annotation'),
    path('v1/device/<str:pk>/', views.DetailsDeviceView.as_view(), name='device'),
    path('v1/tokens/', views.TokenView.as_view(), name='tokens'),
    path('v1/tokens/new', views.TokenNewView.as_view(), name='new_token'),
    path("v1/tokens/<int:pk>/edit", views.EditTokenView.as_view(), name="edit_token"),
    path('v1/tokens/<int:pk>/del', views.TokenDeleteView.as_view(), name='delete_token'),
]

devicehub-django/dashboard/urls.py
from django.urls import path
from dashboard import views 

app_name = 'dashboard'

urlpatterns = [
    path("", views.UnassignedDevicesView.as_view(), name="unassigned_devices"),
    path("<int:pk>/", views.LotDashboardView.as_view(), name="lot"),
    path("search", views.SearchView.as_view(), name="search"),
]

devicehub-django/dhub/urls.py
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    # path('api/', include('snapshot.urls')),
    path("", include("login.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("evidence/", include("evidence.urls")),
    path("device/", include("device.urls")),
    path("admin/", include("admin.urls")),
    path("user/", include("user.urls")),
    path("lot/", include("lot.urls")),
    path('api/', include('api.urls')),
]

if settings.DPP:
    urlpatterns.extend([
        path('dpp/', include('dpp.urls')),
        path('did/', include('did.urls')),
    ])

devicehub-django/login/urls.py
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.urls import path, reverse_lazy
from login.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetConfirmView,
)

app_name = 'login'

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy('login:login'),
        permanent=False)),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
    path('auth/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('auth/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path('auth/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path('auth/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

devicehub-django/lot/urls.py
from django.urls import path
from lot import views

app_name = 'lot'

urlpatterns = [
    path("add/", views.NewLotView.as_view(), name="add"),
    path("delete/<int:pk>/", views.DeleteLotView.as_view(), name="delete"),
    path("edit/<int:pk>/", views.EditLotView.as_view(), name="edit"),
    path("add/devices/", views.AddToLotView.as_view(), name="add_devices"),
    path("del/devices/", views.DelToLotView.as_view(), name="del_devices"),
    path("tag/<int:pk>/", views.LotsTagsView.as_view(), name="tag"),
    path("<int:pk>/document/", views.LotDocumentsView.as_view(), name="documents"),
    path("<int:pk>/document/add", views.LotAddDocumentView.as_view(), name="add_document"),
    path("<int:pk>/annotation", views.LotAnnotationsView.as_view(), name="annotations"),
    path("<int:pk>/annotation/add", views.LotAddAnnotationView.as_view(), name="add_annotation"),
]

devicehub-django/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path("panel/", views.PanelView.as_view(), name="panel"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
]

devicehub-django/dashboard/models.py
from django.db import models

# Create your models here.

devicehub-django/dashboard/views.py
import json

from django.utils.translation import gettext_lazy as _
from django.views.generic.edit import FormView
from django.shortcuts import Http404
from django.db.models import Q

from dashboard.mixins import InventaryMixin, DetailsMixin
from evidence.models import Annotation
from evidence.xapian import search
from device.models import Device
from lot.models import Lot


class UnassignedDevicesView(InventaryMixin):
    template_name = "unassigned_devices.html"
    section = "Unassigned"
    title = _("Unassigned Devices")
    breadcrumb = "Devices / Unassigned Devices"

    def get_devices(self, user, offset, limit):
        return Device.get_unassigned(self.request.user.institution, offset, limit)


class LotDashboardView(InventaryMixin, DetailsMixin):
    template_name = "unassigned_devices.html"
    section = "dashboard_lot"
    title = _("Lot Devices")
    breadcrumb = "Lot / Devices"
    model = Lot

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lot = context.get('object')
        context.update({
            'lot': lot,
        })
        return context

    def get_devices(self, user, offset, limit):
        chids = self.object.devicelot_set.all().values_list(
            "device_id", flat=True
        ).distinct()

        chids_page = chids[offset:offset+limit]
        return [Device(id=x) for x in chids_page], chids.count()


class SearchView(InventaryMixin):
    template_name = "unassigned_devices.html"
    section = "Search"
    title = _("Search Devices")
    breadcrumb = "Devices / Search Devices"

    def get_devices(self, user, offset, limit):
        post = dict(self.request.POST)
        query = post.get("search")

        if not query:
            return [], 0

        matches = search(
            self.request.user.institution,
            query[0],
            offset,
            limit
        )

        if not matches or not matches.size():
            return self.search_hids(query, offset, limit)

        devices = []
        dev_id = []

        for x in matches:
            # devices.append(self.get_annotations(x))
            dev = self.get_annotations(x)
            if dev.id not in dev_id:
                devices.append(dev)
                dev_id.append(dev.id)

        count = matches.size()
        # TODO fix of pagination, the count is not correct
        return devices, count

    def get_annotations(self, xp):
        snap = xp.document.get_data()
        uuid = json.loads(snap).get('uuid')
        return Device.get_annotation_from_uuid(uuid, self.request.user.institution)

    def search_hids(self, query, offset, limit):
        qry = Q()

        for i in query[0].split(" "):
            if i:
                qry |= Q(value__startswith=i)

        chids = Annotation.objects.filter(
            type=Annotation.Type.SYSTEM,
            owner=self.request.user.institution
        ).filter(
            qry
        ).values_list("value", flat=True).distinct()
        chids_page = chids[offset:offset+limit]

        return [Device(id=x) for x in chids_page], chids.count()

devicehub-django/dashboard/templates/base.html
{% load i18n static %}

<!doctype html>
<html lang="en">
  <head>
  {% block head %}
    {% block meta %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="NONE,NOARCHIVE" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Pangea">
    {% endblock %}
    <title>{% block title %}{% if title %}{{ title }} – {% endif %}DeviceHub{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    {% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      html, body {
        height: 100%;
      }

      body {
        display: flex;
        flex-direction: column;
      }

      .main-content {
        flex-grow: 1;
      }

      footer {
        width: 100%;
      }
    </style>

  
    <!-- Custom styles for this template -->
    <link href="{% static "/css/dashboard.css" %}" rel="stylesheet">
    {% endblock %}
  {% endblock %}
  </head>
  <body>
    <header class="navbar navbar-dark sticky-top admin bg-green flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">DEVICEHUB</a>
      <div class="navbar-nav navbar-sub-brand">
         {{ user.institution.name|upper }}
      </div>
      <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <i id="user-avatar" class="bi bi-person-circle"></i>
            <a class="navbar-sub-brand px-3" href="{% url 'user:panel' %}">{{ user.email }}</a>
            <a class="logout" href="{% url 'login:logout' %}">
              <i class="fa-solid fa-arrow-right-from-bracket"></i>
            </a>
        </div>
      </div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-5">
            <ul class="nav flex-column">
	      {% if user.is_admin %}
              <li class="nav-item">
                <a class="admin {% if path in 'panel users' %}active {% endif %}nav-link fw-bold" data-bs-toggle="collapse" data-bs-target="#ul_admin" aria-expanded="false" aria-controls="ul_admin" href="javascript:void()">
                  <i class="bi bi-person-fill-gear icon_sidebar"></i>
                  {% trans 'Admin' %}
                </a>
                <ul class="flex-column mb-2 ul_sidebar accordion-collapse {% if path in 'panel users' %}expanded{% else %}collapse{% endif %}" id="ul_admin" data-bs-parent="#sidebarMenu">
                  <li class="nav-item">
                    <a class="nav-link{% if path == 'panel' %} active2{% endif %}" href="{% url 'admin:panel' %}">
                      {% trans 'Panel' %}
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link{% if path == 'users' %} active2{% endif %}" href="{% url 'admin:users' %}">
                      {% trans 'Users' %}
                    </a>
                  </li>
                </ul>
              </li>
	      {% endif %}
              <li class="nav-item">
                <a class="admin {% if path == 'unassigned_devices' %}active {% endif %}nav-link fw-bold" data-bs-toggle="collapse" data-bs-target="#ul_devices" aria-expanded="false" aria-controls="ul_devices" href="javascript:void()">
                  <i class="bi bi-laptop icon_sidebar"></i>
                  {% trans 'Devices' %}
                </a>
                <ul class="flex-column mb-2 ul_sidebar accordion-collapse {% if path == 'unassigned_devices' %}expanded{% else %}collapse{% endif %}" id="ul_devices" data-bs-parent="#sidebarMenu">
                  <li class="nav-item">
                    <a class="nav-link{% if path == 'unassigned_devices' %} active2{% endif %}" href="{% url 'dashboard:unassigned_devices' %}">
                      {% trans 'Unassigned devices' %}
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="admin {% if path == 'tag' %}active {% endif %}nav-link fw-bold" data-bs-toggle="collapse" data-bs-target="#ul_lots" aria-expanded="false" aria-controls="ul_lots" href="javascript:void()">
                  <i class="bi bi-database icon_sidebar"></i>
                  {% trans 'Lots' %}
                </a>
                <ul class="flex-column mb-2 ul_sidebar accordion-collapse {% if path == 'tag' %}expanded{% else %}collapse{% endif %}" id="ul_lots" data-bs-parent="#sidebarMenu">
                  {% for tag in lot_tags %}
                  <li class="nav-items">
                    <a class="nav-link{% if path == 'tag' %} active2{% endif %}" href="{% url 'lot:tag' tag.id %}">
                      {{ tag.name }}
                    </a>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              <li class="nav-item">
                <a class="admin {% if path in 'upload list' %}active {% endif %}nav-link fw-bold" data-bs-toggle="collapse" data-bs-target="#ul_evidences" aria-expanded="false" aria-controls="ul_evidences" href="javascript:void()">
                  <i class="bi bi-usb-drive icon_sidebar"></i>
                  {% trans 'Evidences' %}
                </a>
                <ul class="flex-column mb-2 ul_sidebar accordion-collapse {% if path in 'upload list' %}expanded{% else %}collapse{% endif %}" id="ul_evidences" data-bs-parent="#sidebarMenu">
                  <li class="nav-item">
                    <a class="nav-link{% if path == 'upload' %} active2{% endif %}" href="{% url 'evidence:upload' %}">
                      {% trans 'Upload one' %}
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link{% if path == 'list' %} active2{% endif %}" href="{% url 'evidence:list' %}">
                      {% trans 'Old evidences' %}
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="admin {% if path in 'import add' %}active {% endif %}nav-link fw-bold" data-bs-toggle="collapse" data-bs-target="#ul_placeholders" aria-expanded="false" aria-controls="ul_placeholders" href="javascript:void()">
                  <i class="bi-menu-button-wide icon_sidebar"></i>
                  {% trans 'Placeholders' %}
                </a>
                <ul class="flex-column mb-2 ul_sidebar accordion-collapse {% if path in 'import add' %}expanded{% else %}collapse{% endif %}" id="ul_placeholders" data-bs-parent="#sidebarMenu">
                  <li class="nav-item">
                    <a class="nav-link{% if path == 'import' %} active2{% endif %}" href="{% url 'evidence:import' %}">
                      {% trans 'Upload Spreadsheet' %}
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link{% if path == 'add' %} active2{% endif %}" href="{% url 'device:add' %}">
                      {% trans 'Create one' %}
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          {% block messages %}
            {% for message in messages %}
              <div class="alert {{ message.tags|default:'info' }} alert-dismissible fade show mt-3" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
              </div>
            {% endfor %}
          {% endblock messages %}
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2">
            <h1 class="h2">{{ title }}</h1>

	    <form method="post" action="{% url 'dashboard:search' %}">
              {% csrf_token %}
              <div class="input-group rounded">
                <input type="search" name="search" class="form-control rounded" placeholder="Search your device..." aria-label="Search" aria-describedby="search-addon" />
        	<span class="input-group-text border-0" id="search-addon">
        	  <i class="fas fa-search"></i>
        	</span>
              </div>
            </form>
	    
          </div>
	  
          <div class="row border-bottom mb-3">
            <div class="col">
              <small style="color:#899bbd"><i>{{ breadcrumb }}</i></small>
            </div>
            <div class="btn-toolbar mb-2 mb-md-0">
            </div>
          </div>

          {% block content %}
          {% endblock content %}

        </main>
      </div>
    </div>

    <!-- Footer -->
  <footer class="footer text-center mt-auto py-3">
    <div class="container">
      <span class="text-muted">{{ commit_id }}</span>
    </div>
  </footer>

    {% block script %}
    <script src="{% static "js/jquery-3.3.1.slim.min.js" %}"></script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block extrascript %}{% endblock %}
    {% endblock %}
  </body>
</html>

devicehub-django/dashboard/templates/pagination.html
{% load i18n %}
{% load range %}

<ul class="pagination">
  {% if page_number > 1 %}
  <li class="previous">
    <a type="button" class="btn btn-grey border border-dark" href="?page=1&limit={{ limit }}">
      &laquo;
    </a>
  </li>
  <li class="previous">
    <a type="button" class="btn btn-grey border border-dark" href="?page={{ page_number|add:-1 }}&limit={{ limit }}">
      {% trans 'Previous' %}
    </a>
  </li>
  {% endif %}

  {% if total_pages > 1 %}

  {% for p in total_pages|range_filter:page_number %}
    <li {% if p == page_number %}class="active"{% endif %}>
      <a type="button" class="btn btn-grey{% if p == page_number %}-selected{% endif %}
                  border border-dark"
       {% if p == page_number or p == "..." %}
          href="#">
       {% else %}
          href="?page={{ p }}&limit={{ limit }}">
       {% endif %}
          {{ p }}
     </a>
   </li>
   {% endfor %}
 {% endif %}

  {% if page_number < total_pages %}
  <li class="previous">
    <a type="button" class="btn btn-grey border border-dark" href="?page={{ page_number|add:+1 }}&limit={{ limit }}">
      {% trans 'Next' %}
    </a>
  </li>
  <li class="previous">
    <a type="button" class="btn btn-grey border border-dark" href="?page={{ total_pages }}&limit={{ limit }}">
      &raquo;
    </a>
  </li>
  {% endif %}
</ul>

devicehub-django/dashboard/templates/unassigned_devices.html
{% extends "base.html" %}
{% load i18n %}
{% load paginacion %}


{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
  <div class="col text-center">
    {% if lot %}
    <a href="{% url 'lot:documents' object.id %}" type="button" class="btn btn-green-admin">
      <i class="bi bi-folder2"></i>
      {% trans 'Documents' %}
    </a>
    {% endif %}
    <a href="{# url 'dashboard:exports' object.id #}" type="button" class="btn btn-green-admin">
      <i class="bi bi-reply"></i>
      {% trans 'Exports' %}
    </a>
    {% if lot %}
    <a href="{% url 'lot:annotations' object.id %}" type="button" class="btn btn-green-admin">
      <i class="bi bi-tag"></i>
      {% trans 'Annotations' %}
    </a>
    {% endif %}
  </div>
</div>

<div class="dataTable-container">
  <form method="post">
  {% csrf_token %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col" data-sortable="">
          select
        </th>
        <th scope="col" data-sortable="">
          shortid
        </th>
        <th scope="col" data-sortable="">
          type
        </th>
        <th scope="col" data-sortable="">
          manufacturer
        </th>
        <th scope="col" data-sortable="">
          model
        </th>
      </tr>
    </thead>
    {% for dev in devices %}
    <tbody>
      <tr>
        <td>
          <input type="checkbox" name="devices" value="{{ dev.id }}" />
        </td>
        <td>
          <a href="{% url 'device:details' dev.id %}">
            {{ dev.shortid }}
          </a>
        </td>
        <td>
            {{ dev.type }}
        </td>
        <td>
            {{ dev.manufacturer }}
        </td>
        <td>
            {{ dev.model }}
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  <button class="btn btn-green-admin" type="submit" value="{% url 'lot:del_devices' %}" name="url">Remove</button> <button class="btn btn-green-admin" type="submit" name="url" value="{% url 'lot:add_devices' %}">add</button>
  </form>
</div>
<div class="row mt-3">
  <div class="col">
    {% render_pagination page total_pages limit %}
  </div>
</div>
{% endblock %}