devicehub-django/api/urls.py
from api import views

from django.urls import path


app_name = 'api'

urlpatterns = [
    path('v1/snapshot/', views.NewSnapshotView.as_view(), name='new_snapshot'),
    path('v1/annotation/<str:pk>/', views.AddAnnotationView.as_view(), name='new_annotation'),
    path('v1/device/<str:pk>/', views.DetailsDeviceView.as_view(), name='device'),
    path('v1/tokens/', views.TokenView.as_view(), name='tokens'),
    path('v1/tokens/new', views.TokenNewView.as_view(), name='new_token'),
    path("v1/tokens/<int:pk>/edit", views.EditTokenView.as_view(), name="edit_token"),
    path('v1/tokens/<int:pk>/del', views.TokenDeleteView.as_view(), name='delete_token'),
]

devicehub-django/dashboard/urls.py
from django.urls import path
from dashboard import views 

app_name = 'dashboard'

urlpatterns = [
    path("", views.UnassignedDevicesView.as_view(), name="unassigned_devices"),
    path("<int:pk>/", views.LotDashboardView.as_view(), name="lot"),
    path("search", views.SearchView.as_view(), name="search"),
]

devicehub-django/device/urls.py
from django.urls import path
from device import views

app_name = 'device'

urlpatterns = [
    path("add/", views.NewDeviceView.as_view(), name="add"),
    path("edit/<str:pk>/", views.EditDeviceView.as_view(), name="edit"),
    path("<str:pk>/", views.DetailsView.as_view(), name="details"),
    path("<str:pk>/annotation/add", views.AddAnnotationView.as_view(), name="add_annotation"),
    path("<str:pk>/document/add", views.AddDocumentView.as_view(), name="add_document"),
    path("<str:pk>/public/", views.PublicDeviceWebView.as_view(), name="device_web"),

]

devicehub-django/dhub/urls.py
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    # path('api/', include('snapshot.urls')),
    path("", include("login.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("evidence/", include("evidence.urls")),
    path("device/", include("device.urls")),
    path("admin/", include("admin.urls")),
    path("user/", include("user.urls")),
    path("lot/", include("lot.urls")),
    path('api/', include('api.urls')),
]

if settings.DPP:
    urlpatterns.extend([
        path('dpp/', include('dpp.urls')),
        path('did/', include('did.urls')),
    ])

devicehub-django/did/urls.py
from django.urls import path
from did import views

app_name = 'did'

urlpatterns = [
    path("<str:pk>", views.PublicDeviceWebView.as_view(), name="device_web"),
]

devicehub-django/evidence/urls.py
# from django.urls import path, include
# from rest_framework.routers import DefaultRouter
# from snapshot.views import SnapshotViewSet

# router = DefaultRouter()
# router.register(r'snapshots', SnapshotViewSet)

# urlpatterns = [
#     path('', include(router.urls)),
# ]
from django.urls import path
from evidence import views 

app_name = 'evidence'

urlpatterns = [
    path("", views.ListEvidencesView.as_view(), name="list"),
    path("upload", views.UploadView.as_view(), name="upload"),
    path("import", views.ImportView.as_view(), name="import"),
    path("<uuid:pk>", views.EvidenceView.as_view(), name="details"),
    path("<uuid:pk>/eraseserver", views.EraseServerView.as_view(), name="erase_server"),
    path("<uuid:pk>/download", views.DownloadEvidenceView.as_view(), name="download"),
    path('annotation/<int:pk>/del', views.AnnotationDeleteView.as_view(), name='delete_annotation'),
]

devicehub-django/device/forms.py
from django import forms
from utils.device import create_annotation, create_doc, create_index
from utils.save_snapshots import move_json, save_in_disk


DEVICE_TYPES = [
    ("Desktop", "Desktop"),
    ("Laptop", "Laptop"),
    ("Server", "Server"),
    ("GraphicCard", "GraphicCard"),
    ("HardDrive", "HardDrive"),
    ("SolidStateDrive", "SolidStateDrive"),
    ("Motherboard", "Motherboard"),
    ("NetworkAdapter", "NetworkAdapter"),
    ("Processor", "Processor"),
    ("RamModule", "RamModule"),
    ("SoundCard", "SoundCard"),
    ("Display", "Display"),
    ("Battery", "Battery"),
    ("Camera", "Camera"),
]


class DeviceForm(forms.Form):
    type = forms.ChoiceField(choices = DEVICE_TYPES, required=False)
    amount = forms.IntegerField(required=False, initial=1)
    custom_id = forms.CharField(required=False)
    name = forms.CharField(required=False)
    value = forms.CharField(required=False)


class BaseDeviceFormSet(forms.BaseFormSet):
    def clean(self):
        for x in self.cleaned_data:
            if x.get("amount"):
                return True
        return False
        
    def save(self, user, commit=True):
        self.user = user
        row = {}
        for f in self.forms:
            d = f.cleaned_data
            if not d:
                continue

            if d.get("type"):
                row["type"] = d["type"]
            if d.get("amount"):
                row["amount"] = d["amount"]
            if d.get("name"):
                row[d["name"]] = d.get("value", '')
            if d.get("custom_id"):
                row['CUSTOM_ID']= d["custom_id"]

        doc = create_doc(row)
        if not commit:
            return doc
        
        path_name = save_in_disk(doc, self.user.institution.name, place="placeholder")
        create_index(doc, self.user)
        create_annotation(doc, user, commit=commit)
        move_json(path_name, self.user.institution.name, place="placeholder")
        
        return doc


DeviceFormSet = forms.formset_factory(form=DeviceForm, formset=BaseDeviceFormSet, extra=1)

devicehub-django/device/views.py
from django.http import JsonResponse
from django.conf import settings
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, Http404
from django.utils.translation import gettext_lazy as _
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    FormView,
)
from django.views.generic.base import TemplateView
from dashboard.mixins import DashboardView, Http403
from evidence.models import Annotation
from lot.models import LotTag
from device.models import Device
from device.forms import DeviceFormSet
if settings.DPP:
    from dpp.models import Proof
    from dpp.api_dlt import PROOF_TYPE


class NewDeviceView(DashboardView, FormView):
    template_name = "new_device.html"
    title = _("New Device")
    breadcrumb = "Device / New Device"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    form_class = DeviceFormSet

    def form_valid(self, form):
        form.save(self.request.user)
        response = super().form_valid(form)
        return response

    def form_invalid(self, form):
        response = super().form_invalid(form)
        return response


# class AddToLotView(DashboardView, FormView):
#     template_name = "list_lots.html"
#     title = _("Add to lots")
#     breadcrumb = "lot / add to lots"
#     success_url = reverse_lazy('dashboard:unassigned_devices')
#     form_class = LotsForm

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         lots = Lot.objects.filter(owner=self.request.user)
#         lot_tags = LotTag.objects.filter(owner=self.request.user)
#         context.update({
#             'lots': lots,
#             'lot_tags':lot_tags,
#         })
#         return context

#     def get_form(self):
#         form = super().get_form()
#         form.fields["lots"].queryset = Lot.objects.filter(owner=self.request.user)
#         return form

#     def form_valid(self, form):
#         form.devices = self.get_session_devices()
#         form.save()
#         response = super().form_valid(form)
#         return response


class EditDeviceView(DashboardView, UpdateView):
    template_name = "new_device.html"
    title = _("Update Device")
    breadcrumb = "Device / Update Device"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    model = Annotation

    def get_form_kwargs(self):
        pk = self.kwargs.get('pk')
        self.object = get_object_or_404(
            self.model,
            pk=pk,
            owner=self.request.user.institution
        )
        self.success_url = reverse_lazy('device:details', args=[pk])
        kwargs = super().get_form_kwargs()
        return kwargs


class DetailsView(DashboardView, TemplateView):
    template_name = "details.html"
    title = _("Device")
    breadcrumb = "Device / Details"
    model = Annotation

    def get(self, request, *args, **kwargs):
        self.pk = kwargs['pk']
        self.object = Device(id=self.pk)
        if not self.object.last_evidence:
            raise Http404
        if self.object.owner != self.request.user.institution:
            raise Http403

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object.initial()
        lot_tags = LotTag.objects.filter(owner=self.request.user.institution)
        dpps = []
        if settings.DPP:
            dpps = Proof.objects.filter(
                uuid__in=self.object.uuids,
                type=PROOF_TYPE["IssueDPP"]
            )
        context.update({
            'object': self.object,
            'snapshot': self.object.get_last_evidence(),
            'lot_tags': lot_tags,
            'dpps': dpps,
        })
        return context


class PublicDeviceWebView(TemplateView):
    template_name = "device_web.html"

    def get(self, request, *args, **kwargs):
        self.pk = kwargs['pk']
        self.object = Device(id=self.pk)

        if not self.object.last_evidence:
            raise Http404

        if self.request.headers.get('Accept') == 'application/json':
            return self.get_json_response()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object.initial()
        context.update({
            'object': self.object
        })
        return context

    @property
    def public_fields(self):
        return {
            'id': self.object.id,
            'shortid': self.object.shortid,
            'uuids': self.object.uuids,
            'hids': self.object.hids,
            'components': self.remove_serial_number_from(self.object.components),
        }

    @property
    def authenticated_fields(self):
        return {
            'serial_number': self.object.serial_number,
            'components': self.object.components,
        }

    def remove_serial_number_from(self, components):
        for component in components:
            if 'serial_number' in component:
                del component['SerialNumber']
        return components

    def get_device_data(self):
        data = self.public_fields
        if self.request.user.is_authenticated:
            data.update(self.authenticated_fields)
        return data

    def get_json_response(self):
        device_data = self.get_device_data()
        return JsonResponse(device_data)


class AddAnnotationView(DashboardView, CreateView):
    template_name = "new_annotation.html"
    title = _("New annotation")
    breadcrumb = "Device / New annotation"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    model = Annotation
    fields = ("key", "value")

    def form_valid(self, form):
        form.instance.owner = self.request.user.institution
        form.instance.user = self.request.user
        form.instance.uuid = self.annotation.uuid
        form.instance.type = Annotation.Type.USER
        response = super().form_valid(form)
        return response

    def get_form_kwargs(self):
        pk = self.kwargs.get('pk')
        institution = self.request.user.institution
        self.annotation = Annotation.objects.filter(
            owner=institution,
            value=pk,
            type=Annotation.Type.SYSTEM
        ).first()

        if not self.annotation:
            raise Http404

        self.success_url = reverse_lazy('device:details', args=[pk])
        kwargs = super().get_form_kwargs()
        return kwargs


class AddDocumentView(DashboardView, CreateView):
    template_name = "new_annotation.html"
    title = _("New Document")
    breadcrumb = "Device / New document"
    success_url = reverse_lazy('dashboard:unassigned_devices')
    model = Annotation
    fields = ("key", "value")

    def form_valid(self, form):
        form.instance.owner = self.request.user.institution
        form.instance.user = self.request.user
        form.instance.uuid = self.annotation.uuid
        form.instance.type = Annotation.Type.DOCUMENT
        response = super().form_valid(form)
        return response

    def get_form_kwargs(self):
        pk = self.kwargs.get('pk')
        institution = self.request.user.institution
        self.annotation = Annotation.objects.filter(
            owner=institution,
            value=pk,
            type=Annotation.Type.SYSTEM
        ).first()

        if not self.annotation:
            raise Http404

        self.success_url = reverse_lazy('device:details', args=[pk])
        kwargs = super().get_form_kwargs()
        return kwargs

devicehub-django/device/templates/details.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <div class="row">
    <div class="col">
      <h3>{{ object.shortid }}</h3>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <ul class="nav nav-tabs nav-tabs-bordered">
        <li class="nav-item">
          <a href="#details" class="nav-link active" data-bs-toggle="tab" data-bs-target="#details">{% trans 'General details' %}</a>
        </li>
        <li class="nav-item">
          <a href="#annotations" class="nav-link" data-bs-toggle="tab" data-bs-target="#annotations">{% trans 'User annotations' %}</a>
        </li>
        <li class="nav-item">
          <a href="#documents" class="nav-link" data-bs-toggle="tab" data-bs-target="#documents">{% trans 'Documents' %}</a>
        </li>
        <li class="nav-item">
          <a href="#lots" class="nav-link" data-bs-toggle="tab" data-bs-target="#lots">{% trans 'Lots' %}</a>
        </li>
        <li class="nav-item">
          <a href="#components" class="nav-link" data-bs-toggle="tab" data-bs-target="#components">{% trans 'Components' %}</a>
        </li>
        <li class="nav-item">
          <a href="#evidences" class="nav-link" data-bs-toggle="tab" data-bs-target="#evidences">{% trans 'Evidences' %}</a>
        </li>
	{% if dpps %}
        <li class="nav-item">
          <a href="#dpps" class="nav-link" data-bs-toggle="tab" data-bs-target="#dpps">{% trans 'Dpps' %}</a>
        </li>
	{% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'device:device_web' object.id %}" target="_blank">Web</a>
        </li>
      </ul>
    </div>
  </div>

  <div class="tab-content pt-2">
    <div class="tab-pane fade show active" id="details">
      <h5 class="card-title">{% trans 'Details' %}</h5>
      <div class="row mb-3">
        <div class="col-lg-3 col-md-4 label">Phid</div>
        <div class="col-lg-9 col-md-8">{{ object.id }}</div>
      </div>

      {% if object.is_eraseserver %}
        <div class="row mb-3">
          <div class="col-lg-3 col-md-4 label">
            {% trans 'Is a erase server' %}
          </div>
          <div class="col-lg-9 col-md-8"></div>
        </div>
      {% endif %}

      <div class="row mb-3">
        <div class="col-lg-3 col-md-4 label">Type</div>
        <div class="col-lg-9 col-md-8">{{ object.type }}</div>
      </div>

      {% if object.is_websnapshot and object.last_user_evidence %}
        {% for k, v in object.last_user_evidence %}
          <div class="row mb-3">
            <div class="col-lg-3 col-md-4 label">{{ k }}</div>
            <div class="col-lg-9 col-md-8">{{ v|default:'' }}</div>
          </div>
        {% endfor %}
      {% else %}
        <div class="row mb-3">
          <div class="col-lg-3 col-md-4 label">
            {% trans 'Manufacturer' %}
          </div>
          <div class="col-lg-9 col-md-8">{{ object.manufacturer|default:'' }}</div>
        </div>

        <div class="row mb-3">
          <div class="col-lg-3 col-md-4 label">
            {% trans 'Model' %}
          </div>
          <div class="col-lg-9 col-md-8">{{ object.model|default:'' }}</div>
        </div>

        <div class="row mb-3">
          <div class="col-lg-3 col-md-4 label">
            {% trans 'Serial Number' %}
          </div>
          <div class="col-lg-9 col-md-8">{{ object.serial_number|default:'' }}</div>
        </div>
      {% endif %}

      <div class="row mb-3">
        <div class="col-lg-3 col-md-4 label">
          {% trans 'Identifiers' %}
        </div>
      </div>
      {% for chid in object.hids %}
        <div class="row mb-3">
          <div class="col">{{ chid|default:'' }}</div>
        </div>
      {% endfor %}
    </div>

    <div class="tab-pane fade" id="annotations">
      <div class="btn-group mt-1 mb-3">
        <a href="{% url 'device:add_annotation' object.pk %}" class="btn btn-primary">
          <i class="bi bi-plus"></i>
          {% trans 'Add new annotation' %}
        </a>
      </div>

      <h5 class="card-title">{% trans 'Annotations' %}</h5>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">
              {% trans 'Key' %}
            </th>
            <th scope="col">
              {% trans 'Value' %}
            </th>
            <th scope="col" data-type="date" data-format="YYYY-MM-DD HH:mm">
              {% trans 'Created on' %}
            </th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for a in object.get_user_annotations %}
            <tr>
              <td>{{ a.key }}</td>
              <td>{{ a.value }}</td>
              <td>{{ a.created }}</td>
              <td></td>
              <td></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="tab-pane fade" id="documents">
      <div class="btn-group mt-1 mb-3">
        <a href="{% url 'device:add_document' object.pk %}" class="btn btn-primary">
          <i class="bi bi-plus"></i>
          {% trans 'Add new document' %}
        </a>
      </div>

      <h5 class="card-title">{% trans 'Documents' %}</h5>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">
              {% trans 'Key' %}
            </th>
            <th scope="col">
              {% trans 'Value' %}
            </th>
            <th scope="col" data-type="date" data-format="YYYY-MM-DD HH:mm">
              {% trans 'Created on' %}
            </th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for a in object.get_user_documents %}
            <tr>
              <td>{{ a.key }}</td>
              <td>{{ a.value }}</td>
              <td>{{ a.created }}</td>
              <td></td>
              <td></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="tab-pane fade" id="lots">
      {% for tag in lot_tags %}
        <h5 class="card-title">{{ tag }}</h5>
        {% for lot in object.lots %}
          {% if lot.type == tag %}
            <div class="row mb-3">
              <div class="col">
                <a href="{% url 'dashboard:lot' lot.id %}">{{ lot.name }}</a>
              </div>
            </div>
          {% endif %}
        {% endfor %}
      {% endfor %}
    </div>

    <div class="tab-pane fade" id="components">
      <h5 class="card-title">{% trans 'Components last evidence' %}</h5>
      <div class="list-group col-6">
        {% for c in object.components %}
          <div class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">{{ c.type }}</h5>
              <small class="text-muted">{{ evidence.created }}</small>
            </div>
            <p class="mb-1">
              {% for k, v in c.items %}
                {% if k not in 'actions,type' %}
                  {{ k }}: {{ v }}<br />
                {% endif %}
              {% endfor %}
            </p>
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="tab-pane fade" id="evidences">
      <h5 class="card-title">{% trans 'List of evidences' %}</h5>
      <div class="list-group col-6">
        {% for snap in object.evidences %}
          <div class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <small class="text-muted">{{ snap.created }}</small>
            </div>
            <p class="mb-1">
              <a href="{% url 'evidence:details' snap.uuid %}">{{ snap.uuid }}</a>
            </p>
          </div>
        {% endfor %}
      </div>
    </div>

    {% if dpps %}
    <div class="tab-pane fade" id="dpps">
      <h5 class="card-title">{% trans 'List of dpps' %}</h5>
      <div class="list-group col">
        {% for d in dpps %}
          <div class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <small class="text-muted">{{ d.timestamp }}</small>
	      <span>{{ d.type }}</span>
            </div>
            <p class="mb-1">
              <a href="{% url 'did:device_web' d.signature %}">{{ d.signature }}</a>
            </p>
          </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </div>
{% endblock %}

{% block extrascript %}
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      // Obtener el hash de la URL (ejemplo: #components)
      const hash = window.location.hash

      // Verificar si hay un hash en la URL
      if (hash) {
        // Buscar el botón o enlace que corresponde al hash y activarlo
        const tabTrigger = document.querySelector(`[data-bs-target="${hash}"]`)

        if (tabTrigger) {
          // Crear una instancia de tab de Bootstrap para activar el tab
          const tab = new bootstrap.Tab(tabTrigger)
          tab.show()
        }
      }
    })
  </script>
{% endblock %}

devicehub-django/device/templates/device_web.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ object.type }}</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" />
    <style>
      body {
        font-size: 0.875rem;
        background-color: #f8f9fa;
        display: flex;
        flex-direction: column;
        min-height: 100vh;
      }
      .custom-container {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        padding: 30px;
        margin-top: 30px;
        flex-grow: 1;
      }
      .section-title {
        color: #7a9f4f;
        border-bottom: 2px solid #9cc666;
        padding-bottom: 10px;
        margin-bottom: 20px;
        font-size: 1.5em;
      }
      .info-row {
        margin-bottom: 10px;
      }
      .info-label {
        font-weight: bold;
        color: #545f71;
      }
      .info-value {
        color: #333;
      }
      .component-card {
        background-color: #f8f9fa;
        border-left: 4px solid #9cc666;
        margin-bottom: 15px;
        transition: all 0.3s ease;
      }
      .component-card:hover {
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
        transform: translateY(-2px);
      }
      .hash-value {
        word-break: break-all;
        background-color: #f3f3f3;
        padding: 5px;
        border-radius: 4px;
        font-family: monospace;
        font-size: 0.9em;
        border: 1px solid #e0e0e0;
      }
      .card-title {
        color: #9cc666;
      }
      .btn-primary {
        background-color: #9cc666;
        border-color: #9cc666;
        padding: 0.1em 2em;
        font-weight: 700;
      }
      .btn-primary:hover {
        background-color: #8ab555;
        border-color: #8ab555;
      }
      .btn-green-user {
        background-color: #c7e3a3;
      }
      .btn-grey {
        background-color: #f3f3f3;
      }
      footer {
        background-color: #545f71;
        color: #ffffff;
        text-align: center;
        padding: 10px 0;
        margin-top: 20px;
      }
    </style>
  </head>
  <body>
    <div class="container custom-container">
      <h1 class="text-center mb-4" style="color: #545f71;">{{ object.manufacturer }} {{ object.type }} {{ object.model }}</h1>

      <div class="row">
        <div class="col-lg-6">
          <h2 class="section-title">Details</h2>
          <div class="info-row row">
            <div class="col-md-4 info-label">Phid</div>
            <div class="col-md-8 info-value">
              <div class="hash-value">{{ object.id }}</div>
            </div>
          </div>
          <div class="info-row row">
            <div class="col-md-4 info-label">Type</div>
            <div class="col-md-8 info-value">{{ object.type }}</div>
          </div>

          {% if object.is_websnapshot %}
            {% for snapshot_key, snapshot_value in object.last_user_evidence %}
              <div class="info-row row">
                <div class="col-md-4 info-label">{{ snapshot_key }}</div>
                <div class="col-md-8 info-value">{{ snapshot_value|default:'' }}</div>
              </div>
            {% endfor %}
          {% else %}
            <div class="info-row row">
              <div class="col-md-4 info-label">Manufacturer</div>
              <div class="col-md-8 info-value">{{ object.manufacturer|default:'' }}</div>
            </div>
            <div class="info-row row">
              <div class="col-md-4 info-label">Model</div>
              <div class="col-md-8 info-value">{{ object.model|default:'' }}</div>
            </div>
            {% if user.is_authenticated %}
              <div class="info-row row">
                <div class="col-md-4 info-label">Serial Number</div>
                <div class="col-md-8 info-value">{{ object.serial_number|default:'' }}</div>
              </div>
            {% endif %}
          {% endif %}
        </div>

        <div class="col-lg-6">
          <h2 class="section-title">Identifiers</h2>
          {% for chid in object.hids %}
            <div class="info-row">
              <div class="hash-value">{{ chid|default:'' }}</div>
            </div>
          {% endfor %}
        </div>
      </div>
      <h2 class="section-title mt-5">Components</h2>
      <div class="row">
        {% for component in object.components %}
          <div class="col-md-6 mb-3">
            <div class="card component-card">
              <div class="card-body">
                <h5 class="card-title">{{ component.type }}</h5>
                <p class="card-text">
                  {% for component_key, component_value in component.items %}
                    {% if component_key not in 'actions,type' %}
                      {% if component_key != 'serialNumber' or user.is_authenticated %}
                        <strong>{{ component_key }}:</strong> {{ component_value }}<br />
                      {% endif %}
                    {% endif %}
                  {% endfor %}
                </p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <footer>
      <p>
        &copy;{% now 'Y' %}eReuse. All rights reserved.
      </p>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

devicehub-django/device/templates/new_annotation.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

{% load django_bootstrap5 %}
<form role="form" method="post">
  {% csrf_token %}
  {% if form.errors %}
  <div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
    <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
    <div class="message">
      {% for field, error in form.errors.items %}
        {{ error }}<br />
      {% endfor %}
      <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
  {% endif %}
  {{ form.management_form }}
  <div class="container" id="formset-container">
    <div class="row mb-2">
      <div class="col"></div>
    </div>
    {% for f in form %}
      <div class="row mb-2">
        <div class="col">
          {% bootstrap_field f %}
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="container">
    <a class="btn btn-grey" href="{% url 'dashboard:unassigned_devices' %}">{% translate "Cancel" %}</a>
    <input class="btn btn-green-admin" type="submit" name="submit" value="{% translate 'Save' %}" />
  </div>

</form>

{% endblock %}