devicehub-django/admin/urls.py
from django.urls import path
from admin import views

app_name = 'admin'

urlpatterns = [
    path("panel/", views.PanelView.as_view(), name="panel"),
    path("users/", views.UsersView.as_view(), name="users"),
    path("users/new", views.CreateUserView.as_view(), name="new_user"),
    path("users/edit/<int:pk>", views.EditUserView.as_view(), name="edit_user"),
    path("users/delete/<int:pk>", views.DeleteUserView.as_view(), name="delete_user"),
    path("institution/<int:pk>", views.InstitutionView.as_view(), name="institution"),
]

devicehub-django/api/urls.py
from api import views

from django.urls import path


app_name = 'api'

urlpatterns = [
    path('v1/snapshot/', views.NewSnapshotView.as_view(), name='new_snapshot'),
    path('v1/annotation/<str:pk>/', views.AddAnnotationView.as_view(), name='new_annotation'),
    path('v1/device/<str:pk>/', views.DetailsDeviceView.as_view(), name='device'),
    path('v1/tokens/', views.TokenView.as_view(), name='tokens'),
    path('v1/tokens/new', views.TokenNewView.as_view(), name='new_token'),
    path("v1/tokens/<int:pk>/edit", views.EditTokenView.as_view(), name="edit_token"),
    path('v1/tokens/<int:pk>/del', views.TokenDeleteView.as_view(), name='delete_token'),
]

devicehub-django/dhub/urls.py
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    # path('api/', include('snapshot.urls')),
    path("", include("login.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("evidence/", include("evidence.urls")),
    path("device/", include("device.urls")),
    path("admin/", include("admin.urls")),
    path("user/", include("user.urls")),
    path("lot/", include("lot.urls")),
    path('api/', include('api.urls')),
]

if settings.DPP:
    urlpatterns.extend([
        path('dpp/', include('dpp.urls')),
        path('did/', include('did.urls')),
    ])

devicehub-django/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path("panel/", views.PanelView.as_view(), name="panel"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
]

devicehub-django/user/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

# Create your models here.


class Institution(models.Model):
    name = models.CharField(
        _("Name"),
        max_length=255,
        blank=False,
        null=False,
        unique=True
    )
    logo = models.CharField(_("Logo"), max_length=255, blank=True, null=True)
    location = models.CharField(_("Location"), max_length=255, blank=True, null=True)
    responsable_person = models.CharField(
        _("Responsable"),
        max_length=255,
        blank=True,
        null=True
    )
    supervisor_person = models.CharField(
        _("Supervisor"),
        max_length=255,
        blank=True,
        null=True
    )


class UserManager(BaseUserManager):
    def create_user(self, email, institution, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            institution=institution
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, institution, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            institution=institution,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        _('Email address'),
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(_("is active"), default=True)
    is_admin = models.BooleanField(_("is admin"), default=False)
    first_name = models.CharField(_("First name"), max_length=255, blank=True, null=True)
    last_name = models.CharField(_("Last name"), max_length=255, blank=True, null=True)
    accept_gdpr = models.BooleanField(default=False)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)


    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['institution']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    @property
    def username(self):
        "Is the email of the user"
        return self.email

devicehub-django/user/forms.py
from django import forms


class SettingsForm(forms.Form):
    token = forms.ChoiceField(
        choices = []
    )
    erasure = forms.ChoiceField(
        choices = [(0, 'Not erasure'),
            ('basic', 'Erasure Basic'),
            ('baseline', 'Erasure Baseline'),
            ('enhanced', 'Erasure Enhanced'),
        ],
    )

    def __init__(self, *args, **kwargs):
        tokens = kwargs.pop('tokens')
        super().__init__(*args, **kwargs)
        tk = [(str(x.token), x.tag) for x in tokens]
        self.fields['token'].choices = tk

devicehub-django/user/views.py
from decouple import config
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import TemplateView
from dashboard.mixins import DashboardView
from django.views.generic.edit import (
    FormView,
)

from user.forms import SettingsForm
from api.models import Token


class PanelView(DashboardView, TemplateView):
    template_name = "panel.html"
    title = _("User")
    breadcrumb = "User / Panel"
    subtitle = "User panel"

    
class SettingsView(DashboardView, FormView):
    template_name = "settings.html"
    title = _("Download Settings")
    breadcrumb = "user / workbench / settings"
    form_class = SettingsForm

    def form_valid(self, form):
        cleaned_data = form.cleaned_data.copy()
        settings_tmpl = "settings.ini"
        path = reverse("api:new_snapshot")
        cleaned_data['url'] = self.request.build_absolute_uri(path)
        
        if config("LEGACY", False):
            cleaned_data['token'] = config.get('TOKEN_LEGACY', '')
            cleaned_data['url'] = config.get('URL_LEGACY', '')
            settings_tmpl = "settings_legacy.ini"
            
        data = render(self.request, settings_tmpl, cleaned_data)
        response = HttpResponse(data.content, content_type="application/text")
        response['Content-Disposition'] = 'attachment; filename={}'.format("settings.ini")
        return response
    
    def get_form_kwargs(self):
        tokens = Token.objects.filter(owner=self.request.user)
        kwargs = super().get_form_kwargs()
        kwargs['tokens'] = tokens
        return kwargs

devicehub-django/admin/templates/admin_panel.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <a href="{% url 'admin:institution' user.institution.pk %}" class="btn btn-green-admin">
      {% translate "Institution" %}
    </a>
  </div>
</div>

{% endblock %}

devicehub-django/admin/templates/admin_users.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
  <div class="col-2">
    <a href="{% url 'admin:new_user' %}" class="btn btn-green-admin">{% translate "Add new user" %}</a>
  </div>
</div>

<div class="row">
  <div class="col">
    <table class="table">
      <thead>
	<tr>
	  <th scope="col">Email</th>
	  <th>is Admin</th>
	  <th></th>
	  <th></th>
	</tr>
      </thead>
      <tbody>
	<tr>
        {% for u in users %}
          <td>{{ u.email }}</td>
          <td>{{ u.is_admin }}</td>
          <td><a href="{% url 'admin:edit_user' u.pk %}"><i class="bi bi-eye"></i></td>
          <td><a href="{% url 'admin:delete_user' u.pk %}" class="text-danger" title="Remove"><i class="bi bi-trash"></i></td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

devicehub-django/admin/templates/delete_user.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

{% load django_bootstrap5 %}
<div class="row mb-3">
  <div class="col">
    Are you sure than want remove the lot {{ object.name }} with {{ object.devices.count }} devices.
  </div>
</div>

<form role="form" method="post">
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
  <div class="message">
    {% for field, error in form.errors.items %}
      {{ error }}<br />
    {% endfor %}
    <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}
{% bootstrap_form form %}
<div class="form-actions-no-box">
  <a class="btn btn-grey" href="{% url 'admin:users' %}">{% translate "Cancel" %}</a>
  <input class="btn btn-green-admin" type="submit" name="submit" value="{% translate 'Delete' %}" />
</div>

</form>
{% endblock %}

devicehub-django/admin/templates/institution.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

{% load django_bootstrap5 %}
<form role="form" method="post">
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
  <div class="message">
    {% for field, error in form.errors.items %}
      {{ error }}<br />
    {% endfor %}
    <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}
{% bootstrap_form form %}
<div class="form-actions-no-box">
  <a class="btn btn-grey" href="{% url 'admin:panel' %}">{% translate "Cancel" %}</a>
  <input class="btn btn-green-admin" type="submit" name="submit" value="{% translate 'Save' %}" />
</div>

</form>
{% endblock %}

devicehub-django/admin/templates/user.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>{{ subtitle }}</h3>
  </div>
</div>

{% load django_bootstrap5 %}
<form role="form" method="post">
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
  <div class="message">
    {% for field, error in form.errors.items %}
      {{ error }}<br />
    {% endfor %}
    <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}
{% bootstrap_form form %}
<div class="form-actions-no-box">
  <a class="btn btn-grey" href="{% url 'admin:users' %}">{% translate "Cancel" %}</a>
  <input class="btn btn-green-admin" type="submit" name="submit" value="{% translate 'Save' %}" />
</div>

</form>
{% endblock %}